# Generated by Django 4.0.6 on 2022-09-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('rol', models.IntegerField(choices=[(1, 'administrador'), (2, 'usuario')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=1500)),
                ('id_comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.comentarios')),
            ],
        ),
        migrations.AddField(
            model_name='comentarios',
            name='id_estudiantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estudiantes'),
        ),
    ]
